### ISSUE TITLE
Error uploading

### ISSUE THREAD

**Issue by fosterc1** [cgkineo/adapt-mediaGallery#1]
Hello

I keep getting Error: Package does not contain a schema when trying to upload the plugin?

Thanks

**Comment by moloko** [comment]
That's correct, it's not been set up for authoring tool compatibility. not sure if that's because there's a specific reason it can't be made authoring tool compatible or it's just that no-one has got around to doing it yet. Probably the latter.

**Comment by moloko** [comment]
see #3
