### ISSUE TITLE
Some 'player options' are not getting applied

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-mediaGallery#4]
Specifically `toggleCaptionsButtonWhenOnlyOne` and `features`. 

I'm not quite sure why this should be as - from what I could tell - the `toggleCaptionsButtonWhenOnlyOne` setting was being passed into the mediaelement player.

Also tested:
- alwaysShowControls
- hideVideoControlsOnLoad
- iPadUseNativeControls

Which all seemed to work fine

**Comment by danielghost** [comment]
@joe-allen-89 - please could you take a look at this alongside ensuring any recent project changes have been incorporated, as previously discussed.

**Comment by moloko** [comment]
about time too 🤣
